[project]
name = "ai-visibility-checker"
version = "0.1.0"
description = "Streamlit-Tool zur Analyse von robots.txt für LLM Visibility"
authors = ["MNW <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "streamlit>=1.45.1"
]