[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
<<<<<<< HEAD
dependencies = [
    "requests>=2.32.4",
    "streamlit>=1.45.1",
]
=======
dependencies = []
>>>>>>> a0bc13b (Initial commit)
